[tox]
min_version = 4.11
env_list = py312
skip_missing_interpreters = true

[testenv]
base_python = python3.12
package = editable
deps =
    -r requirements-test.txt
commands =
    pytest {posargs:tests}
