FROM apache/airflow:2.10.4-python3.11

USER airflow

COPY ingestion-airflow/docker/requirements.txt /requirements.txt
COPY ingestion-core /opt/ingestion-core
RUN pip install --no-cache-dir "apache-airflow==2.10.4" -r /requirements.txt \
    && pip install --no-cache-dir /opt/ingestion-core
